version: '3'
services:
  api:
    image: goobox/goobox-nodes:latest
    command: ["development"]
    ports:
      - "8000:8000"
    volumes:
      - .:/srv/apps/goobox-nodes
      - ./logs/goobox-nodes:/srv/apps/goobox-nodes/logs
    links:
      - postgresql
      - sia

  postgresql:
    image: postgres:alpine
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data/pgdata
      - ./logs/postgresql:/var/log/postgresql

  sia:
    image: goobox/docker-sia:1.4.0-rc4
    command: ["start", "--bootstrap", "--modules", "gctwr"]
    expose:
      - "8000"
    volumes:
      - ./.data/sia:/srv/apps/sia/data
