version: '3'
services:
  api:
    image: goobox/goobox-nodes:latest
    command: ["development"]
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=4088e2a3-bf9c-4246-a19b-66617be962e3
      - DATABASE_URL=postgresql://localuser:localpasswd@postgresql:5432/localdb
      - SIA_API_URL=https://sia:8000
    links:
      - postgresql

  postgresql:
    image: postgres:alpine
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=localuser
      - POSTGRES_PASSWORD=localpasswd
      - POSTGRES_DB=localdb
      - PGDATA=/var/lib/postgresql/data/pgdata
