#!/usr/bin/env python3.6
"""Run script.
"""
import os
import shlex
import sys
from typing import List

from clinner.command import Type as CommandType, command
from clinner.run import Main as ClinnerMain

PYTHON = 'python3.6'
UVICORN = 'uvicorn'
APP = 'goobox_nodes_api'


@command(command_type=CommandType.SHELL,
         parser_opts={'help': 'Start server'})
def start(*args, **kwargs) -> List[List[str]]:
    return [shlex.split(
        f'{UVICORN} '
        f'{APP}.app:app '
        f'--workers=4 '
        f'--bind={os.environ["APP_HOST"]}:{os.environ["APP_PORT"]} '
        f'--pid=uvicorn.pid') + list(args)]


class Main(ClinnerMain):
    commands = (
        'clinner.run.commands.pytest.pytest',
        'clinner.run.commands.prospector.prospector',
        'start',
    )

    def inject_app_settings(self):
        """
        Injecting own settings.
        """
        os.environ.setdefault('APP_HOST', '0.0.0.0')
        os.environ.setdefault('APP_PORT', '8000')


if __name__ == '__main__':
    sys.exit(Main().run())
