version: 2.1

executors:
  builder:
    docker:
      - image: perdy/circleci-python-builder:latest
    environment:
      IMAGE_NAME: goobox/goobox-nodes
  tester:
    docker:
      - image: perdy/circleci-python-builder:latest
      - image: circleci/postgres:9.6.2-alpine
    environment:
      IMAGE_NAME: goobox/goobox-nodes
      SECRET_KEY: 4088e2a3-bf9c-4246-a19b-66617be962e3
      ENVIRONMENT: local
      DATABASE_URL: postgresql://localuser:localpasswd@localhost:5432/localdb
      POSTGRES_USER: localuser
      POSTGRES_PASSWORD: localpasswd
      POSTGRES_DB: localdb
workflows:
  version: 2.1
  test_and_release:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          context:
            aws_ecr
          filters:
            branches:  # ignore any commit on any branch by default
              only: master
          requires:
            - test

jobs:
  build:
    executor: builder
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ checksum "Dockerfile.j2" }}-{{ checksum "poetry.lock" }}
          paths:
            - ~/caches/docker.tar
      - run:
          name: Build Docker image
          command: python make build --production --cache-from ~/caches/docker.tar
      - run:
          name: Save Docker image
          command: builder save $IMAGE_NAME ~/caches/docker.tar
      - save_cache:
          key: v1-{{ checksum "Dockerfile.j2" }}-{{ checksum "poetry.lock" }}
          paths:
            - ~/caches/docker.tar
      - persist_to_workspace:
          root: ~/caches
          paths:
            - docker.tar
  test:
    executor: tester
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - setup_remote_docker
      - run:
          name: Build development image
          command: python make build --cache-from /tmp/workspace/docker.tar
      - run:
          name: Code format (black)
          command: python make black --check .
      - run:
          name: Imports sort (isort)
          command: python make isort --check-only
      - run:
          name: Code lint (flake8)
          command: python make flake8
      - run:
          name: Tests
          command: python make --alone test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
  deploy:
    executor: builder
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - setup_remote_docker
      - run:
          name: Load Docker image
          command: builder load /tmp/workspace/docker.tar
      - run:
          name: Tag image
          command: builder tag $IMAGE_NAME $AWS_ECR_URL/$IMAGE_NAME:production $AWS_ECR_URL/$IMAGE_NAME:$CIRCLE_SHA1
      - run:
          name: Push Docker image
          command: builder push --aws-ecr $AWS_ECR_URL -t $AWS_ECR_URL/$IMAGE_NAME:production -t $AWS_ECR_URL/$IMAGE_NAME:$CIRCLE_SHA1
