"""create_storj_node

Revision ID: 9acc5e8dedb9
Revises:
Create Date: 2018-04-08 16:39:40.514556

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9acc5e8dedb9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'storj_node',
        sa.Column('address', sa.String(), nullable=False),
        sa.Column('country', sa.String(), nullable=False),
        sa.Column('city', sa.String(), nullable=False),
        sa.Column('latitude', sa.Float(), nullable=False),
        sa.Column('longitude', sa.Float(), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('last_seen', sa.DateTime(), nullable=True),
        sa.Column('last_timeout', sa.DateTime(), nullable=True),
        sa.Column('port', sa.Integer(), nullable=False),
        sa.Column('protocol', sa.String(), nullable=True),
        sa.Column('reputation', sa.Integer(), nullable=False),
        sa.Column('response_time', sa.Float(), nullable=False),
        sa.Column('space_available', sa.Integer(), nullable=False),
        sa.Column('timeout_rate', sa.Integer(), nullable=False),
        sa.Column('user_agent', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storj_node')
    # ### end Alembic commands ###
